// UI
export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";
export const CART_START_LOADING = "CART_START_LOADING";
export const CART_STOP_LOADING = "CART_STOP_LOADING";
export const PRODUCTS_START_LOADING = "PRODUCTS_START_LOADING";
export const PRODUCTS_STOP_LOADING = "PRODUCTS_STOP_LOADING";

// Auth
export const AUTH_SET_TOKEN  = "AUTH_SET_TOKEN";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";
export const AUTH_SET_UID = "AUTH_SET_UID";
export const AUTH_REMOVE_UID = "AUTH_REMOVE_UID";

// Products
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const REMOVE_PRODUCT_IN_STORE = "REMOVE_PRODUCT_IN_STORE";
export const ADD_PRODUCT_IN_STORE = "ADD_PRODUCT_IN_STORE";

// Cart
export const SET_CARTS = "SET_CARTS";
export const SET_CART = "SET_CART";
export const ADD_CART_PRODUCT_IN_STORE = "ADD_CART_PRODUCT_IN_STORE";