# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BalajiStore' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BalajiStore
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Auth', '~> 5.3.0'

  target 'BalajiStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BalajiStore-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BalajiStore-tvOS

  target 'BalajiStore-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
